/**
 * incident.schema.ts
 * Esquemas Mongoose para las colecciones de incidentes del sistema principal.
 * NO se duplican datos — apuntan a las mismas colecciones de MongoDB.
 * Se usa strict: false para no interferir con campos que el sistema principal gestiona.
 */

import mongoose, { Schema, Document } from "mongoose";
import { UserDocument } from "../user/user.schema";

// ─── Token de inyección ───────────────────────────────────────────────────────
export const INCIDENT_MODEL = "Incidentes_denuncia"; // colección: incidentes_denuncias
export const ESTADO_INCIDENTE_MODEL = "estado_incidente"; // colección: estado_incidentes

// ─── Tipos de documento ───────────────────────────────────────────────────────
export type IncidentDocument = Document & {
  categoria?: mongoose.Types.ObjectId | CategoriaDocument; // Soporta ambos
  subcategoria?: mongoose.Types.ObjectId | SubcategoriaDocument; // Soporta ambos
  ciudadano?: mongoose.Types.ObjectId | UserDocument; // Soporta ambos
  estado?: mongoose.Types.ObjectId | EstadoIncidenteDocument; // Soporta ambos
  descripcion?: string;
  foto?: string[];
  evidencia?: string[];
  direccion_geo?: { nombre?: string; latitud?: number; longitud?: number };
  prioridad?: string;
  createdAt?: Date;
  updatedAt?: Date;
  [key: string]: any;
};

export type EstadoIncidenteDocument = Document & {
  nombre?: string;
  emoji?: string;
  [key: string]: any;
};

// ─── Schema de Incidente ──────────────────────────────────────────────────────
// strict: false → permite que Mongoose lea y escriba todos los campos existentes
// sin validar contra este esquema parcial.
export const IncidentSchema = new Schema(
  {
    // Campos que los use-cases leen o escriben directamente
    categoria: { type: Schema.Types.ObjectId, ref: "categoria" },
    subcategoria: { type: Schema.Types.ObjectId, ref: "subcategoria" },
    ciudadano: { type: Schema.Types.ObjectId, ref: "user" },
    estado: { type: Schema.Types.ObjectId, ref: "estado_incidente" },
    descripcion: { type: String },
    foto: [{ type: String }],
    evidencia: [{ type: String }],
    direccion_geo: {
      nombre: { type: String },
      latitud: { type: Number },
      longitud: { type: Number },
    },
    prioridad: { type: String },
  },
  {
    strict: false, // No rechazar campos desconocidos del sistema principal
    timestamps: true,
  },
);

// ─── Schema de Estado de Incidente ───────────────────────────────────────────
export const EstadoIncidenteSchema = new Schema(
  {
    nombre: { type: String },
    emoji: { type: String },
  },
  {
    strict: false,
    timestamps: true,
  },
);

/**
 * categoria.schema.ts
 * Schemas Mongoose para las colecciones 'categorias', 'subcategorias' y 'encargado_categorias' del sistema principal.
 * NO se duplican datos — apuntan a las mismas colecciones via mismo MONGODB_URI.
 * strict: false → Mongoose lee todos los campos sin rechazar los que el sistema principal gestiona.
 */

// ─── Tokens de inyección ─────────────────────────────────────────────────────
/** modelo 'categoria' → colección 'categorias' */
export const CATEGORIA_MODEL = "categoria";
/** modelo 'subcategoria' → colección 'subcategorias' */
export const SUBCATEGORIA_MODEL = "subcategoria";
/** modelo 'encargado_categoria' → colección 'encargado_categorias' */
export const ENCARGADO_CATEGORIA_MODEL = "encargado_categoria";

// ─── Tipos de documento ───────────────────────────────────────────────────────
export type CategoriaDocument = Document & {
  nombre: string;
  descripcion: string;
  icono?: string;
  createdAt?: Date;
  updatedAt?: Date;
  [key: string]: any; // Permite campos adicionales del sistema principal
};

export type SubcategoriaDocument = Document & {
  categoria: mongoose.Types.ObjectId;
  nombre: string;
  descripcion: string;
  icono?: string;
  createdAt?: Date;
  updatedAt?: Date;
  [key: string]: any;
};

export type EncargadoCategoriaDocument = Document & {
  encargado: mongoose.Types.ObjectId[];
  categoria: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
  [key: string]: any;
};

// ─── Schema de Categoria ──────────────────────────────────────────────────────
export const CategoriaSchema = new Schema(
  {
    nombre: { type: String, required: true },
    descripcion: { type: String, required: true },
    icono: { type: String },
  },
  {
    strict: false, // No rechazar campos extra del sistema principal
    timestamps: true,
  },
);

// Métodos estáticos para compatibilidad con sistema principal
CategoriaSchema.statics.isProtected = function (method: string): boolean {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};

CategoriaSchema.statics.isAutogenerated = function (method: string): boolean {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};

// ─── Schema de Subcategoria ───────────────────────────────────────────────────
export const SubcategoriaSchema = new Schema(
  {
    categoria: {
      type: Schema.Types.ObjectId,
      ref: CATEGORIA_MODEL,
      required: true,
    },
    nombre: { type: String, required: true },
    descripcion: { type: String, required: true },
    icono: { type: String },
  },
  {
    strict: false,
    timestamps: true,
  },
);

SubcategoriaSchema.statics.isProtected = function (method: string): boolean {
  const protectedMethods = [
    "get",
    "post",
    "put",
    "delete",
    "createBatch",
    "updateBatch",
  ];
  return protectedMethods.includes(method);
};

SubcategoriaSchema.statics.isAutogenerated = function (
  method: string,
): boolean {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};

// ─── Schema de Encargado Categoria ───────────────────────────────────────────
export const EncargadoCategoriaSchema = new Schema(
  {
    encargado: [{ type: Schema.Types.ObjectId, ref: "user" }],
    categoria: {
      type: Schema.Types.ObjectId,
      ref: CATEGORIA_MODEL,
      required: true,
    },
  },
  {
    strict: false,
    timestamps: true,
  },
);

EncargadoCategoriaSchema.statics.isProtected = function (
  method: string,
): boolean {
  const protectedMethods = ["get", "post", "put", "delete"];
  return protectedMethods.includes(method);
};

EncargadoCategoriaSchema.statics.isAutogenerated = function (
  method: string,
): boolean {
  const autogeneratedMethods = ["get", "post", "put", "delete"];
  return autogeneratedMethods.includes(method);
};
